/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimulacaoIndexRouteImport } from './routes/simulacao.index'
import { Route as SimulacaoResultadoRouteImport } from './routes/simulacao.resultado'
import { Route as ApiTtsStreamRouteImport } from './routes/api/tts-stream'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as ApiRealtimeSessionRouteImport } from './routes/api/realtime-session'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAssinaturaRouteImport } from './routes/_authenticated/assinatura'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPracticeIndexRouteImport } from './routes/_authenticated/practice.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicSimulationChatRouteImport } from './routes/api/public/simulation-chat'
import { Route as ApiPublicRealtimeSessionRouteImport } from './routes/api/public/realtime-session'
import { Route as AuthenticatedSettingsOnboardingRouteImport } from './routes/_authenticated/settings.onboarding'
import { Route as AuthenticatedPracticeFillInBlankRouteImport } from './routes/_authenticated/practice.fill-in-blank'
import { Route as AuthenticatedChatConversationIdRouteImport } from './routes/_authenticated/chat.$conversationId'
import { Route as AuthenticatedAssinaturaRetornoRouteImport } from './routes/_authenticated/assinatura.retorno'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminRetentionRouteImport } from './routes/_authenticated/admin.retention'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminIdentityRouteImport } from './routes/_authenticated/admin.identity'
import { Route as ApiPublicMercadoPagoWebhookRouteImport } from './routes/api/public/mercado-pago/webhook'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin.users.$userId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacaoIndexRoute = SimulacaoIndexRouteImport.update({
  id: '/simulacao/',
  path: '/simulacao/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacaoResultadoRoute = SimulacaoResultadoRouteImport.update({
  id: '/simulacao/resultado',
  path: '/simulacao/resultado',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsStreamRoute = ApiTtsStreamRouteImport.update({
  id: '/api/tts-stream',
  path: '/api/tts-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeSessionRoute = ApiRealtimeSessionRouteImport.update({
  id: '/api/realtime-session',
  path: '/api/realtime-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssinaturaRoute = AuthenticatedAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticeIndexRoute =
  AuthenticatedPracticeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPracticeRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicSimulationChatRoute = ApiPublicSimulationChatRouteImport.update({
  id: '/api/public/simulation-chat',
  path: '/api/public/simulation-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRealtimeSessionRoute =
  ApiPublicRealtimeSessionRouteImport.update({
    id: '/api/public/realtime-session',
    path: '/api/public/realtime-session',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsOnboardingRoute =
  AuthenticatedSettingsOnboardingRouteImport.update({
    id: '/settings/onboarding',
    path: '/settings/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticeFillInBlankRoute =
  AuthenticatedPracticeFillInBlankRouteImport.update({
    id: '/fill-in-blank',
    path: '/fill-in-blank',
    getParentRoute: () => AuthenticatedPracticeRoute,
  } as any)
const AuthenticatedChatConversationIdRoute =
  AuthenticatedChatConversationIdRouteImport.update({
    id: '/chat/$conversationId',
    path: '/chat/$conversationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssinaturaRetornoRoute =
  AuthenticatedAssinaturaRetornoRouteImport.update({
    id: '/retorno',
    path: '/retorno',
    getParentRoute: () => AuthenticatedAssinaturaRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRetentionRoute =
  AuthenticatedAdminRetentionRouteImport.update({
    id: '/retention',
    path: '/retention',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminIdentityRoute =
  AuthenticatedAdminIdentityRouteImport.update({
    id: '/identity',
    path: '/identity',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicMercadoPagoWebhookRoute =
  ApiPublicMercadoPagoWebhookRouteImport.update({
    id: '/api/public/mercado-pago/webhook',
    path: '/api/public/mercado-pago/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/assinatura': typeof AuthenticatedAssinaturaRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/practice': typeof AuthenticatedPracticeRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/realtime-session': typeof ApiRealtimeSessionRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/tts-stream': typeof ApiTtsStreamRoute
  '/simulacao/resultado': typeof SimulacaoResultadoRoute
  '/simulacao/': typeof SimulacaoIndexRoute
  '/admin/identity': typeof AuthenticatedAdminIdentityRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/retention': typeof AuthenticatedAdminRetentionRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/assinatura/retorno': typeof AuthenticatedAssinaturaRetornoRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/practice/fill-in-blank': typeof AuthenticatedPracticeFillInBlankRoute
  '/settings/onboarding': typeof AuthenticatedSettingsOnboardingRoute
  '/api/public/realtime-session': typeof ApiPublicRealtimeSessionRoute
  '/api/public/simulation-chat': typeof ApiPublicSimulationChatRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/practice/': typeof AuthenticatedPracticeIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/mercado-pago/webhook': typeof ApiPublicMercadoPagoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/assinatura': typeof AuthenticatedAssinaturaRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/realtime-session': typeof ApiRealtimeSessionRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/tts-stream': typeof ApiTtsStreamRoute
  '/simulacao/resultado': typeof SimulacaoResultadoRoute
  '/simulacao': typeof SimulacaoIndexRoute
  '/admin/identity': typeof AuthenticatedAdminIdentityRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/retention': typeof AuthenticatedAdminRetentionRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/assinatura/retorno': typeof AuthenticatedAssinaturaRetornoRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/practice/fill-in-blank': typeof AuthenticatedPracticeFillInBlankRoute
  '/settings/onboarding': typeof AuthenticatedSettingsOnboardingRoute
  '/api/public/realtime-session': typeof ApiPublicRealtimeSessionRoute
  '/api/public/simulation-chat': typeof ApiPublicSimulationChatRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/practice': typeof AuthenticatedPracticeIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/mercado-pago/webhook': typeof ApiPublicMercadoPagoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/assinatura': typeof AuthenticatedAssinaturaRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/realtime-session': typeof ApiRealtimeSessionRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/tts-stream': typeof ApiTtsStreamRoute
  '/simulacao/resultado': typeof SimulacaoResultadoRoute
  '/simulacao/': typeof SimulacaoIndexRoute
  '/_authenticated/admin/identity': typeof AuthenticatedAdminIdentityRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/retention': typeof AuthenticatedAdminRetentionRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/_authenticated/assinatura/retorno': typeof AuthenticatedAssinaturaRetornoRoute
  '/_authenticated/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/_authenticated/practice/fill-in-blank': typeof AuthenticatedPracticeFillInBlankRoute
  '/_authenticated/settings/onboarding': typeof AuthenticatedSettingsOnboardingRoute
  '/api/public/realtime-session': typeof ApiPublicRealtimeSessionRoute
  '/api/public/simulation-chat': typeof ApiPublicSimulationChatRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/practice/': typeof AuthenticatedPracticeIndexRoute
  '/_authenticated/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/mercado-pago/webhook': typeof ApiPublicMercadoPagoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/assinatura'
    | '/dashboard'
    | '/onboarding'
    | '/planos'
    | '/practice'
    | '/api/chat'
    | '/api/realtime-session'
    | '/api/stt'
    | '/api/tts'
    | '/api/tts-stream'
    | '/simulacao/resultado'
    | '/simulacao/'
    | '/admin/identity'
    | '/admin/leads'
    | '/admin/retention'
    | '/admin/users'
    | '/assinatura/retorno'
    | '/chat/$conversationId'
    | '/practice/fill-in-blank'
    | '/settings/onboarding'
    | '/api/public/realtime-session'
    | '/api/public/simulation-chat'
    | '/admin/'
    | '/practice/'
    | '/admin/users/$userId'
    | '/api/public/mercado-pago/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/assinatura'
    | '/dashboard'
    | '/onboarding'
    | '/planos'
    | '/api/chat'
    | '/api/realtime-session'
    | '/api/stt'
    | '/api/tts'
    | '/api/tts-stream'
    | '/simulacao/resultado'
    | '/simulacao'
    | '/admin/identity'
    | '/admin/leads'
    | '/admin/retention'
    | '/admin/users'
    | '/assinatura/retorno'
    | '/chat/$conversationId'
    | '/practice/fill-in-blank'
    | '/settings/onboarding'
    | '/api/public/realtime-session'
    | '/api/public/simulation-chat'
    | '/admin'
    | '/practice'
    | '/admin/users/$userId'
    | '/api/public/mercado-pago/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/assinatura'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/planos'
    | '/_authenticated/practice'
    | '/api/chat'
    | '/api/realtime-session'
    | '/api/stt'
    | '/api/tts'
    | '/api/tts-stream'
    | '/simulacao/resultado'
    | '/simulacao/'
    | '/_authenticated/admin/identity'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/retention'
    | '/_authenticated/admin/users'
    | '/_authenticated/assinatura/retorno'
    | '/_authenticated/chat/$conversationId'
    | '/_authenticated/practice/fill-in-blank'
    | '/_authenticated/settings/onboarding'
    | '/api/public/realtime-session'
    | '/api/public/simulation-chat'
    | '/_authenticated/admin/'
    | '/_authenticated/practice/'
    | '/_authenticated/admin/users/$userId'
    | '/api/public/mercado-pago/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiRealtimeSessionRoute: typeof ApiRealtimeSessionRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiTtsStreamRoute: typeof ApiTtsStreamRoute
  SimulacaoResultadoRoute: typeof SimulacaoResultadoRoute
  SimulacaoIndexRoute: typeof SimulacaoIndexRoute
  ApiPublicRealtimeSessionRoute: typeof ApiPublicRealtimeSessionRoute
  ApiPublicSimulationChatRoute: typeof ApiPublicSimulationChatRoute
  ApiPublicMercadoPagoWebhookRoute: typeof ApiPublicMercadoPagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacao/': {
      id: '/simulacao/'
      path: '/simulacao'
      fullPath: '/simulacao/'
      preLoaderRoute: typeof SimulacaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacao/resultado': {
      id: '/simulacao/resultado'
      path: '/simulacao/resultado'
      fullPath: '/simulacao/resultado'
      preLoaderRoute: typeof SimulacaoResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts-stream': {
      id: '/api/tts-stream'
      path: '/api/tts-stream'
      fullPath: '/api/tts-stream'
      preLoaderRoute: typeof ApiTtsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime-session': {
      id: '/api/realtime-session'
      path: '/api/realtime-session'
      fullPath: '/api/realtime-session'
      preLoaderRoute: typeof ApiRealtimeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinatura': {
      id: '/_authenticated/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AuthenticatedAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/': {
      id: '/_authenticated/practice/'
      path: '/'
      fullPath: '/practice/'
      preLoaderRoute: typeof AuthenticatedPracticeIndexRouteImport
      parentRoute: typeof AuthenticatedPracticeRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/simulation-chat': {
      id: '/api/public/simulation-chat'
      path: '/api/public/simulation-chat'
      fullPath: '/api/public/simulation-chat'
      preLoaderRoute: typeof ApiPublicSimulationChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/realtime-session': {
      id: '/api/public/realtime-session'
      path: '/api/public/realtime-session'
      fullPath: '/api/public/realtime-session'
      preLoaderRoute: typeof ApiPublicRealtimeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/onboarding': {
      id: '/_authenticated/settings/onboarding'
      path: '/settings/onboarding'
      fullPath: '/settings/onboarding'
      preLoaderRoute: typeof AuthenticatedSettingsOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/fill-in-blank': {
      id: '/_authenticated/practice/fill-in-blank'
      path: '/fill-in-blank'
      fullPath: '/practice/fill-in-blank'
      preLoaderRoute: typeof AuthenticatedPracticeFillInBlankRouteImport
      parentRoute: typeof AuthenticatedPracticeRoute
    }
    '/_authenticated/chat/$conversationId': {
      id: '/_authenticated/chat/$conversationId'
      path: '/chat/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof AuthenticatedChatConversationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinatura/retorno': {
      id: '/_authenticated/assinatura/retorno'
      path: '/retorno'
      fullPath: '/assinatura/retorno'
      preLoaderRoute: typeof AuthenticatedAssinaturaRetornoRouteImport
      parentRoute: typeof AuthenticatedAssinaturaRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/retention': {
      id: '/_authenticated/admin/retention'
      path: '/retention'
      fullPath: '/admin/retention'
      preLoaderRoute: typeof AuthenticatedAdminRetentionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/identity': {
      id: '/_authenticated/admin/identity'
      path: '/identity'
      fullPath: '/admin/identity'
      preLoaderRoute: typeof AuthenticatedAdminIdentityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/mercado-pago/webhook': {
      id: '/api/public/mercado-pago/webhook'
      path: '/api/public/mercado-pago/webhook'
      fullPath: '/api/public/mercado-pago/webhook'
      preLoaderRoute: typeof ApiPublicMercadoPagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users/$userId': {
      id: '/_authenticated/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
  }
}

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIdentityRoute: typeof AuthenticatedAdminIdentityRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminRetentionRoute: typeof AuthenticatedAdminRetentionRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIdentityRoute: AuthenticatedAdminIdentityRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminRetentionRoute: AuthenticatedAdminRetentionRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAssinaturaRouteChildren {
  AuthenticatedAssinaturaRetornoRoute: typeof AuthenticatedAssinaturaRetornoRoute
}

const AuthenticatedAssinaturaRouteChildren: AuthenticatedAssinaturaRouteChildren =
  {
    AuthenticatedAssinaturaRetornoRoute: AuthenticatedAssinaturaRetornoRoute,
  }

const AuthenticatedAssinaturaRouteWithChildren =
  AuthenticatedAssinaturaRoute._addFileChildren(
    AuthenticatedAssinaturaRouteChildren,
  )

interface AuthenticatedPracticeRouteChildren {
  AuthenticatedPracticeFillInBlankRoute: typeof AuthenticatedPracticeFillInBlankRoute
  AuthenticatedPracticeIndexRoute: typeof AuthenticatedPracticeIndexRoute
}

const AuthenticatedPracticeRouteChildren: AuthenticatedPracticeRouteChildren = {
  AuthenticatedPracticeFillInBlankRoute: AuthenticatedPracticeFillInBlankRoute,
  AuthenticatedPracticeIndexRoute: AuthenticatedPracticeIndexRoute,
}

const AuthenticatedPracticeRouteWithChildren =
  AuthenticatedPracticeRoute._addFileChildren(
    AuthenticatedPracticeRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAssinaturaRoute: typeof AuthenticatedAssinaturaRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRouteWithChildren
  AuthenticatedChatConversationIdRoute: typeof AuthenticatedChatConversationIdRoute
  AuthenticatedSettingsOnboardingRoute: typeof AuthenticatedSettingsOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAssinaturaRoute: AuthenticatedAssinaturaRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRouteWithChildren,
  AuthenticatedChatConversationIdRoute: AuthenticatedChatConversationIdRoute,
  AuthenticatedSettingsOnboardingRoute: AuthenticatedSettingsOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  ApiRealtimeSessionRoute: ApiRealtimeSessionRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiTtsStreamRoute: ApiTtsStreamRoute,
  SimulacaoResultadoRoute: SimulacaoResultadoRoute,
  SimulacaoIndexRoute: SimulacaoIndexRoute,
  ApiPublicRealtimeSessionRoute: ApiPublicRealtimeSessionRoute,
  ApiPublicSimulationChatRoute: ApiPublicSimulationChatRoute,
  ApiPublicMercadoPagoWebhookRoute: ApiPublicMercadoPagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
