/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimulacaoIndexRouteImport } from './routes/simulacao.index'
import { Route as SimulacaoResultadoRouteImport } from './routes/simulacao.resultado'
import { Route as ApiTtsStreamRouteImport } from './routes/api/tts-stream'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPracticeIndexRouteImport } from './routes/_authenticated/practice.index'
import { Route as ApiPublicSimulationChatRouteImport } from './routes/api/public/simulation-chat'
import { Route as AuthenticatedSettingsOnboardingRouteImport } from './routes/_authenticated/settings.onboarding'
import { Route as AuthenticatedPracticeFillInBlankRouteImport } from './routes/_authenticated/practice.fill-in-blank'
import { Route as AuthenticatedChatConversationIdRouteImport } from './routes/_authenticated/chat.$conversationId'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacaoIndexRoute = SimulacaoIndexRouteImport.update({
  id: '/simulacao/',
  path: '/simulacao/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacaoResultadoRoute = SimulacaoResultadoRouteImport.update({
  id: '/simulacao/resultado',
  path: '/simulacao/resultado',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsStreamRoute = ApiTtsStreamRouteImport.update({
  id: '/api/tts-stream',
  path: '/api/tts-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticeIndexRoute =
  AuthenticatedPracticeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPracticeRoute,
  } as any)
const ApiPublicSimulationChatRoute = ApiPublicSimulationChatRouteImport.update({
  id: '/api/public/simulation-chat',
  path: '/api/public/simulation-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsOnboardingRoute =
  AuthenticatedSettingsOnboardingRouteImport.update({
    id: '/settings/onboarding',
    path: '/settings/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticeFillInBlankRoute =
  AuthenticatedPracticeFillInBlankRouteImport.update({
    id: '/fill-in-blank',
    path: '/fill-in-blank',
    getParentRoute: () => AuthenticatedPracticeRoute,
  } as any)
const AuthenticatedChatConversationIdRoute =
  AuthenticatedChatConversationIdRouteImport.update({
    id: '/chat/$conversationId',
    path: '/chat/$conversationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/practice': typeof AuthenticatedPracticeRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/tts-stream': typeof ApiTtsStreamRoute
  '/simulacao/resultado': typeof SimulacaoResultadoRoute
  '/simulacao/': typeof SimulacaoIndexRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/practice/fill-in-blank': typeof AuthenticatedPracticeFillInBlankRoute
  '/settings/onboarding': typeof AuthenticatedSettingsOnboardingRoute
  '/api/public/simulation-chat': typeof ApiPublicSimulationChatRoute
  '/practice/': typeof AuthenticatedPracticeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/tts-stream': typeof ApiTtsStreamRoute
  '/simulacao/resultado': typeof SimulacaoResultadoRoute
  '/simulacao': typeof SimulacaoIndexRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/practice/fill-in-blank': typeof AuthenticatedPracticeFillInBlankRoute
  '/settings/onboarding': typeof AuthenticatedSettingsOnboardingRoute
  '/api/public/simulation-chat': typeof ApiPublicSimulationChatRoute
  '/practice': typeof AuthenticatedPracticeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/tts-stream': typeof ApiTtsStreamRoute
  '/simulacao/resultado': typeof SimulacaoResultadoRoute
  '/simulacao/': typeof SimulacaoIndexRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/_authenticated/practice/fill-in-blank': typeof AuthenticatedPracticeFillInBlankRoute
  '/_authenticated/settings/onboarding': typeof AuthenticatedSettingsOnboardingRoute
  '/api/public/simulation-chat': typeof ApiPublicSimulationChatRoute
  '/_authenticated/practice/': typeof AuthenticatedPracticeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/onboarding'
    | '/practice'
    | '/api/chat'
    | '/api/stt'
    | '/api/tts'
    | '/api/tts-stream'
    | '/simulacao/resultado'
    | '/simulacao/'
    | '/admin/leads'
    | '/chat/$conversationId'
    | '/practice/fill-in-blank'
    | '/settings/onboarding'
    | '/api/public/simulation-chat'
    | '/practice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/onboarding'
    | '/api/chat'
    | '/api/stt'
    | '/api/tts'
    | '/api/tts-stream'
    | '/simulacao/resultado'
    | '/simulacao'
    | '/admin/leads'
    | '/chat/$conversationId'
    | '/practice/fill-in-blank'
    | '/settings/onboarding'
    | '/api/public/simulation-chat'
    | '/practice'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/practice'
    | '/api/chat'
    | '/api/stt'
    | '/api/tts'
    | '/api/tts-stream'
    | '/simulacao/resultado'
    | '/simulacao/'
    | '/_authenticated/admin/leads'
    | '/_authenticated/chat/$conversationId'
    | '/_authenticated/practice/fill-in-blank'
    | '/_authenticated/settings/onboarding'
    | '/api/public/simulation-chat'
    | '/_authenticated/practice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiTtsStreamRoute: typeof ApiTtsStreamRoute
  SimulacaoResultadoRoute: typeof SimulacaoResultadoRoute
  SimulacaoIndexRoute: typeof SimulacaoIndexRoute
  ApiPublicSimulationChatRoute: typeof ApiPublicSimulationChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacao/': {
      id: '/simulacao/'
      path: '/simulacao'
      fullPath: '/simulacao/'
      preLoaderRoute: typeof SimulacaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacao/resultado': {
      id: '/simulacao/resultado'
      path: '/simulacao/resultado'
      fullPath: '/simulacao/resultado'
      preLoaderRoute: typeof SimulacaoResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts-stream': {
      id: '/api/tts-stream'
      path: '/api/tts-stream'
      fullPath: '/api/tts-stream'
      preLoaderRoute: typeof ApiTtsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/': {
      id: '/_authenticated/practice/'
      path: '/'
      fullPath: '/practice/'
      preLoaderRoute: typeof AuthenticatedPracticeIndexRouteImport
      parentRoute: typeof AuthenticatedPracticeRoute
    }
    '/api/public/simulation-chat': {
      id: '/api/public/simulation-chat'
      path: '/api/public/simulation-chat'
      fullPath: '/api/public/simulation-chat'
      preLoaderRoute: typeof ApiPublicSimulationChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/onboarding': {
      id: '/_authenticated/settings/onboarding'
      path: '/settings/onboarding'
      fullPath: '/settings/onboarding'
      preLoaderRoute: typeof AuthenticatedSettingsOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/fill-in-blank': {
      id: '/_authenticated/practice/fill-in-blank'
      path: '/fill-in-blank'
      fullPath: '/practice/fill-in-blank'
      preLoaderRoute: typeof AuthenticatedPracticeFillInBlankRouteImport
      parentRoute: typeof AuthenticatedPracticeRoute
    }
    '/_authenticated/chat/$conversationId': {
      id: '/_authenticated/chat/$conversationId'
      path: '/chat/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof AuthenticatedChatConversationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPracticeRouteChildren {
  AuthenticatedPracticeFillInBlankRoute: typeof AuthenticatedPracticeFillInBlankRoute
  AuthenticatedPracticeIndexRoute: typeof AuthenticatedPracticeIndexRoute
}

const AuthenticatedPracticeRouteChildren: AuthenticatedPracticeRouteChildren = {
  AuthenticatedPracticeFillInBlankRoute: AuthenticatedPracticeFillInBlankRoute,
  AuthenticatedPracticeIndexRoute: AuthenticatedPracticeIndexRoute,
}

const AuthenticatedPracticeRouteWithChildren =
  AuthenticatedPracticeRoute._addFileChildren(
    AuthenticatedPracticeRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRouteWithChildren
  AuthenticatedChatConversationIdRoute: typeof AuthenticatedChatConversationIdRoute
  AuthenticatedSettingsOnboardingRoute: typeof AuthenticatedSettingsOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRouteWithChildren,
  AuthenticatedChatConversationIdRoute: AuthenticatedChatConversationIdRoute,
  AuthenticatedSettingsOnboardingRoute: AuthenticatedSettingsOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiTtsStreamRoute: ApiTtsStreamRoute,
  SimulacaoResultadoRoute: SimulacaoResultadoRoute,
  SimulacaoIndexRoute: SimulacaoIndexRoute,
  ApiPublicSimulationChatRoute: ApiPublicSimulationChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
